config/routes.rb
Rails.application.routes.draw do
  #  resources :sheets
  #  resources :projects

  post "users/login"
  get "users/login"
  get  "users/logout"
  get "users/index"
  get "users/getone"
  post "users/index"
  post "users/new"
  post "users/update"
  post "users/delete_domaine"

  get "user_notifications/index"
  post "user_notifications/new"
  post "user_notifications/update"

  get "roles/index"
  get "roles/getone"
  post "roles/index"
  post "roles/new"
  post "roles/update"

  get "domaines/index"
  post "domaines/index"
  post "domaines/new"
  post "domaines/update"

  get "versions/index"
  get "versions/getone"
  post "versions/index"
  post "versions/new"
  post "versions/update"

  get "computers/index"
  post "computers/delete"

  get "listes/index"
  get "listes/getone"
  post "listes/index"
  post "listes/new"
  post "listes/update"

  get "kanbans/index"
  get "kanbans/parametrize"
  get "kanbans/getone"
  post "kanbans/index"
  post "kanbans/parametrize"
  post "kanbans/new"
  post "kanbans/update"

  get "type_fiches/index"
  get "type_fiches/getone"
  get "type_fiches/show"
  post "type_fiches/index"
  post "type_fiches/new"
  post "type_fiches/update"

  get "fiches/new"
  get "fiches/edit"
  get "fiches/get_fiches_filtered"
  post "fiches/update"
  post "fiches/move"
  post "fiches/uploadfile"
  post "fiches/deleteupload"

  get  "projects/index"
  get  "projects/welcome"
  post  "projects/welcome"
  get  "projects/getone"
  post  "projects/create"
  post  "projects/index"
  post  "projects/new"
  post  "projects/update"

  post  "lockobjects/delete"

  get "sheets/index"
  get "sheets/edit"
  post "sheets/index"
  post "sheets/add_sheet"
  post "sheets/add_folder"
  post "sheets/edit"
  post "sheets/update"
  post "sheets/updatediag"
  post "sheets/rename"
  post "sheets/delete"
  post "sheets/paste"
  post "sheets/holdunhold"

  get "funcandscreens/index"
  post "funcandscreens/index"
  post "funcandscreens/delete"

  get "domelements/index"
  get "domelements/update"
  post "domelements/copy"
  post "domelements/massiveinsert"
  get "domelements/proxy"

  get "procedures/index"
  get "procedures/update"
  get "procedures/edit"
  post "procedures/edit"
  get "procedures/listtoaddtotest"
  get "procedures/whocallaction"
  post "procedures/whocallaction"
  post "procedures/copy"
  get "procedures/incampain"

  get "actions/index"
  post "actions/index"
  get "actions/getone"
  get "actions/whocallaction"
  post "actions/whocallaction"
  post "actions/new"
  post "actions/update"
  post "actions/duplicate"

  get "required_gems/index"
  post "required_gems/update"

  get "tests/index"
  post "tests/index"
  get "tests/edit"
  post "tests/edit"
  post "tests/rename"
  post "tests/add_folder"
  post "tests/addtest"
  post "tests/delete"
  post "tests/update"
  post "tests/paste"
  post "tests/addsubatddfolder"
  post "tests/addatddsteptest"
  post "tests/pasteatddelement"


  post "teststeps/addnew"
  post "teststeps/addcode"
  post "teststeps/delete"
  post "teststeps/reorder"
  post "teststeps/changeparamvalue"
  post "teststeps/paste"
  post "teststeps/tododone"
  post "teststeps/validatestructure"
  post "teststeps/hold"
  post "teststeps/unhold"
  post "teststeps/changeparamatddvalue"
  post "teststeps/validarrayatdd"

  get "configuration_variables/index"
  post "configuration_variables/index"
  get "configuration_variables/getone"
  post "configuration_variables/new"
  post "configuration_variables/update"

  get "environnement_variables/index"
  get "environnement_variables/getone"
  post "environnement_variables/index"
  get "environnement_variables/update"

  get "environnements/index"
  post "environnements/index"
  get "environnements/update"

  get "data_set_variables/index"
  get "data_set_variables/getone"
  post "data_set_variables/index"
  get "data_set_variables/update"

  get "data_sets/index"
  post "data_sets/index"
  get "data_sets/update"

  get "appium_caps/index"
  post "appium_caps/index"
  get "appium_caps/update"

  get "appium_cap_values/index"
  post "appium_cap_values/index"
  get "appium_cap_values/getone"
  get "appium_cap_values/update"

  get "test_constantes/index"
  post "test_constantes/index"
  get "test_constantes/update"

  get  "node_forced_configs/index"
  post  "node_forced_configs/update"

  get  "default_user_configs/index"
  post  "default_user_configs/update"

  get  "releases/index"
  get  "releases/getone"
  post  "releases/new"
  post  "releases/update"
  post  "cycles/new"
  post  "cycles/update"

  get  "campains/index"
  post  "campains/index"
  get  "campains/edit"
  post  "campains/edit"
  get  "campains/cover"
  post  "campains/cover"
  get  "campains/wscampainresults"
  post  "campains/new"
  post  "campains/update"
  post  "campains/paste"
  post  "campains/submit"
  post  "campains/wslaunch"

  post "campain_test_suites/addnew"
  post "campain_test_suites/delete"
  post "campain_test_suites/reorder"
  post "campain_test_suites/paste"

  get  "campain_test_suite_forced_configs/index"
  post "campain_test_suite_forced_configs/update"

  get  "runs/index"
  post  "runs/index"
  post  "runs/delete"
  post  "runs/stop"
  post  "runs/unlock"

  get  "run_configs/testindex"
  post "run_configs/testupdate"

  get  "run_step_results/index"
  post  "run_step_results/index"
  get  "run_step_results/comment"
  post  "run_step_results/comment"
  post  "run_step_results/force"
  post  "run_step_results/setrefscreenshot"

  get "run_suite_schemes/index"

  get "ws/getfuncandscreens"
  get "ws/getdomelements"
  get "ws/getactions"
  get "ws/getprocedures"
  get "ws/gettests"
  get "ws/getruncode"
  get "ws/gettokenforrun"
  post "ws/postresult"
  get "ws/getrunconfigs"
  get "ws/declarecomputer"
  post "ws/undeclarecomputer"
  get "ws/isdeclaredcomputer"
  post "ws/unlocksubrun"
  get "ws/getnodestatus"
  get "ws/getsuitestatus"
  post "ws/storedata"
  get "ws/getdata"
  post "ws/uploadimage"

  get "home" => "users#login"
  get "" => "users#login"


  resources :domelements do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :environnement_variables do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :environnements do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :data_set_variables do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :data_sets do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :appium_caps do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :appium_cap_values do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :test_constantes do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :procedures do
    member do
      delete :destroy
      post :create
      put :update
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/data_set.rb
class DataSet < ApplicationRecord
  belongs_to :domaine
  has_many :data_set_variables, :dependent => :destroy
end

app/controllers/data_sets_controller.rb
class DataSetsController < ApplicationController
  before_action :require_login
  

 
  def index
    @message=params[:message]
    if params[:ok].to_s == 'ko'
      @OK = false
    else
      @OK = true
    end
    name = params["name"].to_s
    description = params["description"].to_s
    filter = ""
    if name != ""
      filter += " and name like '%#{name}%'"
    end
    if description != ""
      filter += " and description like '%#{description}%'"
    end
     
    @data_sets = DataSet.where("domaine_id = #{@domaine} and version_id = #{@selectedversion}   #{filter}").all
  end  
  
  def create
    @message=nil
    name = params["name"].to_s
    description = params["description"].to_s
    if DataSet.where("domaine_id = #{@domaine}  and version_id = #{@selectedversion} and name = '#{name}'").first == nil
      @data_set = DataSet.new
      @data_set.name = name
      @data_set.description = description
      @data_set.domaine_id = @domaine
      @data_set.version_id = @currentversion
	  @data_set.is_default = 0
      @data_set.save
      @data_set.current_id = @data_set.id
      @data_set.save
      configuration_variable_env = ConfigurationVariable.where(:name => '$data_set', :domaine_id => @domaine).first
      if configuration_variable_env != nil
        configuration_variable_value = ConfigurationVariableValue.where(:configuration_variable_id => configuration_variable_env.id, :domaine_id => @domaine, :value => name).first
        if configuration_variable_value == nil
          configuration_variable_value = ConfigurationVariableValue.new
          configuration_variable_value.domaine_id = @domaine
          configuration_variable_value.configuration_variable_id = configuration_variable_env.id
          configuration_variable_value.value = name
          configuration_variable_value.is_modifiable = 0
          configuration_variable_value.save
        end
      end

      other_env_on_version = DataSet.where("domaine_id = #{@domaine}  and version_id = #{@selectedversion} and id != #{@data_set.id}").first 
      if other_env_on_version != nil
      data_setvariables = DataSetVariable.where("domaine_id = #{@domaine}  and data_set_id = #{other_env_on_version.id}").all
      if data_setvariables != nil
        data_setvariables.each do |data_setvariable|
          variable = data_setvariable.dup
          variable.value = nil
          variable.data_set_id = @data_set.id
          variable.save
        end
      end
      end
    else
      @message = (I18n.t "message.nom_existant").gsub("{1}", name)
    end
    @data_sets = DataSet.where(:domaine_id => @domaine, :version_id => @selectedversion).all
  
    respond_to do |format|
      if @data_set !=nil 
        format.html { redirect_to @data_set, notice: 'DataSet was successfully created.' }
        format.js   {}
        format.json { render json: @data_set, status: :created, location: @data_set }
      else
        format.html { redirect_to  controller: 'data_sets', action: 'index'  , message: @message, ok: 'ko' }
        format.json { render json: @data_set.errors, status: :unprocessable_entity }
      end
    end

  end


  def destroy
  	@message=nil
	@data_set = DataSet.where(:id => params[:id]).first
    name = @data_set.name
    if @data_set != nil
      @data_set.destroy
      init_env_vars = DataSetVariable.where(:domaine_id => @domaine, :data_set_id => nil).all
      init_env_vars.each do |init_env_var|
        if DataSetVariable.where(:domaine_id => @domaine, :init_variable_id => init_env_var.id).first == nil
          init_env_var.destroy
        end
      end
	configuration_variable_env = ConfigurationVariable.where(:domaine_id => @domaine, :name => '$data_set').first
	if configuration_variable_env != nil
	  ConfigurationVariableValue.where(:domaine_id => @domaine, :configuration_variable_id => configuration_variable_env.id, :value => name).delete_all
	end
    end
    @data_sets = DataSet.where(:domaine_id => @domaine, :version_id => @selectedversion).all
  end
  
  def update
    @message=nil
    idelement = params["idelement"]
    @majid = idelement
    name = params["name"]
    description = params["description"]
    
    @data_set = DataSet.where(:id => idelement).first
    name_before = @data_set.name
    name_exists = false
    if name_before != name
      if DataSet.where("domaine_id = #{@domaine} and version_id = #{@selectedversion} and name = '#{name}' and id != #{idelement}").first != nil
        name_exists = true
      end
    end
    if @data_set != nil and name_exists == false
      oldname = @data_set.name
      DataSet.where(:domaine_id => @domaine, :name => oldname).update_all(:name => name, :description => description)
      @data_sets = DataSet.where(:domaine_id => @domaine, :version_id => @selectedversion).all
      @majid = @data_set.id
      @message = I18n.t "message.maj_effectuee"
      @OK=true
      configuration_variable_env = ConfigurationVariable.where(:name => '$data_set', :domaine_id => @domaine).first
      if configuration_variable_env != nil
        configuration_variable_value = ConfigurationVariableValue.where(:configuration_variable_id => configuration_variable_env.id, :domaine_id => @domaine, :value => name_before).first
        if configuration_variable_value == nil
          configuration_variable_value = ConfigurationVariableValue.new
          configuration_variable_value.domaine_id = @domaine
          configuration_variable_value.configuration_variable_id = configuration_variable_env.id
          configuration_variable_value.value = name
          configuration_variable_value.is_modifiable = 0
          configuration_variable_value.save
        else
          configuration_variable_value.value = name
          configuration_variable_value.save
        end
      end
    else
      @data_sets = DataSet.where(:domaine_id => @domaine, :version_id => @selectedversion).all
      @message = I18n.t "message.operation_impossible"
      @OK=false
    end
  end  
  


  
end

app/views/data_sets/_data_set.html.erb
<% if @message != nil and data_set.id.to_s == @majid.to_s %>
   <span id='idspanmessage' class='<% if @OK %>succesMessage<% else %>errorMessage<% end %>' onclick='this.parentNode.removeChild(this)' style='vertical-align: top;'><%= @message %>&nbsp;<b>x</b></span>
  <% end %> 

<div class="ligthline">
<div class="inline">


 <input <% if @can_manage_jdd == 0 or data_set.is_default == 1 %>disabled<% end %> pattern="[A-Za-z0-9_]{2,50}" maxlength='50' onKeyUp="formatascode(this)" required size=40  class='inputboxlist' type="text" spellcheck='false' name="name" id="iname<%= data_set.id %>" value="<%= data_set.name %>" title="<%= t('ecr_data_set.format_titre') %>" onKeyDown='showupdateform("<%= data_set.id %>");' onchange='checknamevalidity("<%= data_set.id %>", "<%= data_set.name %>");'/>

  <input <% if @can_manage_jdd == 0 %>disabled<% end %> type="text" spellcheck='false' class='inputboxlist' name="description" id="idescription<%= data_set.id %>" size='100' value="<%= data_set.description %>" onKeyDown='showupdateform("<%= data_set.id %>");'/>

  <% if @can_manage_jdd == 1 %>
	<form onsubmit="startloader();" action="/data_sets/update" data-remote="true" rel="nofollow" data-method="put" style="display: none;" id="formupdt<%= data_set.id %>">
            <input type="hidden" name="idelement" value="<%= data_set.id %>"/>
            <input type="hidden" name="name" id="name<%= data_set.id %>" value=""/>
            <input type="hidden" name="description" id="description<%= data_set.id %>" value=""/>
            <input class="btnvalid" title="<%= t('valider') %>" type="submit" value=""  onclick="document.getElementById('name<%= data_set.id %>').value=document.getElementById('iname<%= data_set.id %>').value;document.getElementById('description<%= data_set.id %>').value=document.getElementById('idescription<%= data_set.id %>').value;" style='vertical-align: top;' onmouseover='checknamevalidity("<%= data_set.id %>", "<%= data_set.name %>");'/>
	</form>
<% end %>
  
<%=  link_to image_tag("/assets/icones/btnvariable1.png"), { :controller => :data_set_variables, :action => :getone, :envone => data_set.id}, class: "btn", onclick: "startloader();", title: t('variables')  %>
  
<% if @can_manage_jdd == 1  and data_set.is_default == 0  %>
    <%= button_to "",  data_set_path(data_set), remote: true, method: :delete, form: {onsubmit: "startloader();"}, data: { confirm: "#{t('ecr_data_set.confirme_supp')} #{data_set.name}?"  }, class: "btndel", title: t('supprimer') %>
<% end %>


	

</div>
</div>
<script>
          setTimeout(function () {
            elem = document.getElementById('idspanmessage');
            if (elem!=null) {
              elem.parentNode.removeChild(elem);
            }
        }, 2000);
</script>  

app/views/data_sets/_head.html.erb
<span class="titleStyle" style="color:#161616"><b>&nbsp;&nbsp;<%= t('ecr_data_set.nouvel_data_set') %>&nbsp;&nbsp;</b></span> 
<br>
<div style="display: inline-block">
<div style="display: inline">
<form onsubmit="startloader();" class="new_data_set" id="new_data_set" action="/data_sets" accept-charset="UTF-8" data-remote="true" method="post" style="display: inline;margin-left: 7px;">
 <input  pattern="[A-Za-z0-9_]{2,50}" maxlength='50' onKeyUp="formatascode(this)" required size=40 class='inputboxlist' type="text" spellcheck='false' name="name" id="data_set_data_set_name" placeholder="<%= t('nom') %>" title="<%= t('ecr_data_set.format_titre') %>"/>

 <textarea spellcheck='false' class='inputboxlist' name="description" id="data_set_data_set_description" rows='1' cols='100' placeholder="<%= t('description') %>"></textarea>
<% if @can_manage_jdd == 1 %>
  <input type="submit" class="btnadd" title="<%= t('ajouter') %>" value="" ></input>
  <% end %>
</form>  
  <button class="btnsearch" onclick="startloader();searchenv();" title="<%= t('chercher') %>"></button>
</div>
</div>	  
    
<form id="formsearch" action="../data_sets/index" method="post">
	<input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token"/>
    <input type="hidden" name="description" id="searchdesc" value=""/>
    <input type="hidden" name="name" id="searchname" value=""/>   
</form>   

app/views/data_sets/create.js.erb
$("<%= escape_javascript(render @data_set) %>").appendTo("#data_sets");
$('#data_set_data_set_name').val('');
$('#data_set_data_set_description').val('');
stoploader();

app/views/data_sets/destroy.js.erb
$('#data_sets').html('<%= j(render @data_sets, locals: {data_set: @data_set} )%>');
stoploader();

app/views/data_sets/index.html.erb
<script type="application/javascript"> 
function searchenv() {
    document.getElementById('data_set_data_set_name').required=false;
    document.getElementById('searchname').value=document.getElementById('data_set_data_set_name').value;
    document.getElementById('searchdesc').value=document.getElementById('data_set_data_set_description').value;
    document.getElementById('formsearch').submit();
}
</script>

<div id="scrollablecontent">
	<div >
		<div class="popupadd">
			 <%= render :partial => 'data_sets/head' %>    
		</div> 
		
		<div id="data_sets" >	
			<% if @data_sets != nil %>    
				<%= render  @data_sets %>
			<% end %>
		</div>
	</div>
</div>

app/views/data_sets/update.js.erb
$('#data_sets').html('<%= j(render @data_sets, locals: {data_set: @data_set} )%>');
stoploader();