config/routes.rb
Rails.application.routes.draw do
  #  resources :sheets
  #  resources :projects

  post "users/login"
  get "users/login"
  get  "users/logout"
  get "users/index"
  get "users/getone"
  post "users/index"
  post "users/new"
  post "users/update"
  post "users/delete_domaine"

  get "user_notifications/index"
  post "user_notifications/new"
  post "user_notifications/update"

  get "roles/index"
  get "roles/getone"
  post "roles/index"
  post "roles/new"
  post "roles/update"

  get "domaines/index"
  post "domaines/index"
  post "domaines/new"
  post "domaines/update"

  get "versions/index"
  get "versions/getone"
  post "versions/index"
  post "versions/new"
  post "versions/update"

  get "computers/index"
  post "computers/delete"

  get "listes/index"
  get "listes/getone"
  post "listes/index"
  post "listes/new"
  post "listes/update"

  get "kanbans/index"
  get "kanbans/parametrize"
  get "kanbans/getone"
  post "kanbans/index"
  post "kanbans/parametrize"
  post "kanbans/new"
  post "kanbans/update"

  get "type_fiches/index"
  get "type_fiches/getone"
  get "type_fiches/show"
  post "type_fiches/index"
  post "type_fiches/new"
  post "type_fiches/update"

  get "fiches/new"
  get "fiches/edit"
  get "fiches/get_fiches_filtered"
  post "fiches/update"
  post "fiches/move"
  post "fiches/uploadfile"
  post "fiches/deleteupload"

  get  "projects/index"
  get  "projects/welcome"
  post  "projects/welcome"
  get  "projects/getone"
  post  "projects/create"
  post  "projects/index"
  post  "projects/new"
  post  "projects/update"

  post  "lockobjects/delete"

  get "sheets/index"
  get "sheets/edit"
  post "sheets/index"
  post "sheets/add_sheet"
  post "sheets/add_folder"
  post "sheets/edit"
  post "sheets/update"
  post "sheets/updatediag"
  post "sheets/rename"
  post "sheets/delete"
  post "sheets/paste"
  post "sheets/holdunhold"

  get "funcandscreens/index"
  post "funcandscreens/index"
  post "funcandscreens/delete"

  get "domelements/index"
  get "domelements/update"
  post "domelements/copy"
  post "domelements/massiveinsert"
  get "domelements/proxy"

  get "procedures/index"
  get "procedures/update"
  get "procedures/edit"
  post "procedures/edit"
  get "procedures/listtoaddtotest"
  get "procedures/whocallaction"
  post "procedures/whocallaction"
  post "procedures/copy"
  get "procedures/incampain"

  get "actions/index"
  post "actions/index"
  get "actions/getone"
  get "actions/whocallaction"
  post "actions/whocallaction"
  post "actions/new"
  post "actions/update"
  post "actions/duplicate"

  get "required_gems/index"
  post "required_gems/update"

  get "tests/index"
  post "tests/index"
  get "tests/edit"
  post "tests/edit"
  post "tests/rename"
  post "tests/add_folder"
  post "tests/addtest"
  post "tests/delete"
  post "tests/update"
  post "tests/paste"
  post "tests/addsubatddfolder"
  post "tests/addatddsteptest"
  post "tests/pasteatddelement"


  post "teststeps/addnew"
  post "teststeps/addcode"
  post "teststeps/delete"
  post "teststeps/reorder"
  post "teststeps/changeparamvalue"
  post "teststeps/paste"
  post "teststeps/tododone"
  post "teststeps/validatestructure"
  post "teststeps/hold"
  post "teststeps/unhold"
  post "teststeps/changeparamatddvalue"
  post "teststeps/validarrayatdd"

  get "configuration_variables/index"
  post "configuration_variables/index"
  get "configuration_variables/getone"
  post "configuration_variables/new"
  post "configuration_variables/update"

  get "environnement_variables/index"
  get "environnement_variables/getone"
  post "environnement_variables/index"
  get "environnement_variables/update"

  get "environnements/index"
  post "environnements/index"
  get "environnements/update"

  get "data_set_variables/index"
  get "data_set_variables/getone"
  post "data_set_variables/index"
  get "data_set_variables/update"

  get "data_sets/index"
  post "data_sets/index"
  get "data_sets/update"

  get "appium_caps/index"
  post "appium_caps/index"
  get "appium_caps/update"

  get "appium_cap_values/index"
  post "appium_cap_values/index"
  get "appium_cap_values/getone"
  get "appium_cap_values/update"

  get "test_constantes/index"
  post "test_constantes/index"
  get "test_constantes/update"

  get  "node_forced_configs/index"
  post  "node_forced_configs/update"

  get  "default_user_configs/index"
  post  "default_user_configs/update"

  get  "releases/index"
  get  "releases/getone"
  post  "releases/new"
  post  "releases/update"
  post  "cycles/new"
  post  "cycles/update"

  get  "campains/index"
  post  "campains/index"
  get  "campains/edit"
  post  "campains/edit"
  get  "campains/cover"
  post  "campains/cover"
  get  "campains/wscampainresults"
  post  "campains/new"
  post  "campains/update"
  post  "campains/paste"
  post  "campains/submit"
  post  "campains/wslaunch"

  post "campain_test_suites/addnew"
  post "campain_test_suites/delete"
  post "campain_test_suites/reorder"
  post "campain_test_suites/paste"

  get  "campain_test_suite_forced_configs/index"
  post "campain_test_suite_forced_configs/update"

  get  "runs/index"
  post  "runs/index"
  post  "runs/delete"
  post  "runs/stop"
  post  "runs/unlock"

  get  "run_configs/testindex"
  post "run_configs/testupdate"

  get  "run_step_results/index"
  post  "run_step_results/index"
  get  "run_step_results/comment"
  post  "run_step_results/comment"
  post  "run_step_results/force"
  post  "run_step_results/setrefscreenshot"

  get "run_suite_schemes/index"

  get "ws/getfuncandscreens"
  get "ws/getdomelements"
  get "ws/getactions"
  get "ws/getprocedures"
  get "ws/gettests"
  get "ws/getruncode"
  get "ws/gettokenforrun"
  post "ws/postresult"
  get "ws/getrunconfigs"
  get "ws/declarecomputer"
  post "ws/undeclarecomputer"
  get "ws/isdeclaredcomputer"
  post "ws/unlocksubrun"
  get "ws/getnodestatus"
  get "ws/getsuitestatus"
  post "ws/storedata"
  get "ws/getdata"
  post "ws/uploadimage"

  get "home" => "users#login"
  get "" => "users#login"


  resources :domelements do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :environnement_variables do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :environnements do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :data_set_variables do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :data_sets do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :appium_caps do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :appium_cap_values do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :test_constantes do
    member do
      delete :destroy
      post :create
      put :update
    end
  end

  resources :procedures do
    member do
      delete :destroy
      post :create
      put :update
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/data_set_variable.rb
class DataSetVariable < ApplicationRecord
  belongs_to :domaine
end

app/controllers/data_set_variables_controller.rb
class DataSetVariablesController < ApplicationController
  before_action :require_login
  

 
  def index
    envone = (params["envone"]!= nil ? params["envone"] : flash["envone"]).to_s
    envtwo = (params["envtwo"]!= nil ? params["envtwo"] : flash["envtwo"]).to_s
    @message=params[:message]
    if params[:ok].to_s == 'ko'
      @OK = false
    else
      @OK = true
    end
    @name = params["name"].to_s
    @description = params["description"].to_s
    filter = ""
    if @name != ""
      filter += " and data_set_variables.name like '%#{@name}%'"
    end
    if @description != ""
      filter += " and data_set_variables.description like '%#{@description}%'"
    end
    @envone = nil
    @envtwo = nil
    if envone != ""
      @envone = DataSet.where("id = #{envone}").first
    else
      @envone = DataSet.where("domaine_id = #{@domaine} and version_id = #{@selectedversion}").first
      if @envone != nil then envone = @envone.id end
    end
    if envtwo != ""
      @envtwo = DataSet.where("id = #{envtwo}").first
    end

    @data_sets = DataSet.where("domaine_id = #{@domaine} and version_id = #{@selectedversion}").all 
    @data_set_variables = nil

    if @envone != nil and @envtwo == nil
      @data_set_variables = DataSetVariable.select("data_set_variables.*, envone.value as valueone, envone.id as idvarone").joins("INNER JOIN data_set_variables as envone on envone.domaine_id = data_set_variables.domaine_id and envone.data_set_id = #{@envone.id} and envone.init_variable_id = data_set_variables.id ").where("data_set_variables.domaine_id = #{@domaine} and data_set_variables.project_id=#{@selectedproject} and data_set_variables.data_set_id is null #{filter}").order("data_set_variables.name").all
    end	
    if @envone != nil and @envtwo != nil
      if params[:do].to_s == "paste"
        envtwo_variables = DataSetVariable.where("domaine_id = #{@domaine} and project_id=#{@selectedproject} and data_set_id = #{@envtwo.id}").all
        envtwo_variables.each do |envtwo_variable|
          envone_variable = DataSetVariable.where("domaine_id = #{@domaine} and project_id=#{@selectedproject} and data_set_id = #{@envone.id} and init_variable_id = #{envtwo_variable.init_variable_id}").first
          envtwo_variable.value = envone_variable.value
          envtwo_variable.save
        end
      end
      
      @data_set_variables = DataSetVariable
      .select("data_set_variables.*, envone.value as valueone, envone.id as idvarone, envtwo.value as valuetwo, envtwo.id as idvartwo")
      .joins("INNER JOIN data_set_variables as envone on envone.domaine_id = data_set_variables.domaine_id and envone.data_set_id = #{@envone.id} and envone.init_variable_id = data_set_variables.id")
      .joins("INNER JOIN data_set_variables as envtwo on envtwo.domaine_id = data_set_variables.domaine_id and envtwo.data_set_id = #{@envtwo.id} and envtwo.init_variable_id = data_set_variables.id ")
      .where("data_set_variables.domaine_id = #{@domaine} and data_set_variables.project_id=#{@selectedproject} and data_set_variables.data_set_id is null #{filter}").order("data_set_variables.name").all
    end	
  end  

  def getone
    flash[:envone] = params[:envone].to_s
    redirect_to controller: 'data_set_variables', action: 'index'
  end
  
  def create
    envone = (params["envone"]!= nil ? params["envone"] : flash["envone"]).to_s
    envtwo = (params["envtwo"]!= nil ? params["envtwo"] : flash["envtwo"]).to_s
    @message=nil
    name = params["name"].to_s
    description = params["description"].to_s
    
    nom_variable_existant = false
    first_env_on_version = DataSet.where("domaine_id = #{@domaine} and version_id = #{@selectedversion}").first
    if first_env_on_version != nil then envid = first_env_on_version.id else envid = nil end
    stringvariable = Commun.get_variables_string
    if stringvariable.index(name + "$") != nil or
        name.start_with? "$domelement" or
        DataSetVariable.where(:domaine_id => @domaine, :data_set_id => envid, :name => name).first != nil  or
        EnvironnementVariable.where(:domaine_id => @domaine, :environnement_id => nil, :init_variable_id => nil, :name => name).first != nil  or
        ConfigurationVariable.where("domaine_id = #{@domaine} and name = '#{name}'").first != nil or 
        TestConstante.where("domaine_id = #{@domaine} and name = '#{name}'").first != nil then
      nom_variable_existant = true
    end
    
    
    if nom_variable_existant == false
      data_set_variable = DataSetVariable.new
      data_set_variable.init_variable_id = nil
      data_set_variable.value = nil
      data_set_variable.name = name
      data_set_variable.description = description
      data_set_variable.domaine_id = @domaine
      data_set_variable.project_id = @selectedproject
      data_set_variable.data_set_id = nil
      data_set_variable.is_used = 0
      data_set_variable.is_numeric = 0
      data_set_variable.is_boolean = 0
      data_set_variable.save
      data_sets = DataSet.where(:domaine_id => @domaine, :version_id => @selectedversion).all
      if data_sets != nil
        data_sets.each do |data_set|
          variable = DataSetVariable.where(:domaine_id => @domaine, :data_set_id => data_set.id, :init_variable_id =>  data_set_variable.id).first
          if variable == nil
            variable = DataSetVariable.new
            variable.init_variable_id = data_set_variable.id
            variable.value = nil
            variable.name = name
            variable.description = description
            variable.domaine_id = @domaine
            variable.project_id = @selectedproject
            variable.data_set_id = data_set.id
            variable.is_used =0
            variable.save
          else
            variable.name = name
            variable.description = description
            variable.save
          end
        end
      end
    else
      @message = (I18n.t "message.nom_existant").gsub("{1}", name)
    end
    
    @envone = nil
    @envtwo = nil
    if envone != ""
      @envone = DataSet.where("id = #{envone}").first
    else
      @firstenv = DataSet.where("domaine_id = #{@domaine} and version_id = #{@selectedversion}").first
      if @firstenv != nil then firstenv = @firstenv.id else firstenv = 0 end
    end
    if envtwo != ""
      @envtwo = DataSet.where("id = #{envtwo}").first
    end
    @data_sets = DataSet.where("domaine_id = #{@domaine} and version_id = #{@selectedversion}").all 
    if @envone == nil  
      @data_set_variable = data_set_variable
      @data_set_variables = DataSetVariable.select("data_set_variables.*, envone.value as valueone, envone.id as idvarone").joins("INNER JOIN data_set_variables as envone on envone.domaine_id = data_set_variables.domaine_id and envone.data_set_id = #{firstenv} and envone.init_variable_id = data_set_variables.id ").where("data_set_variables.domaine_id = #{@domaine} and data_set_variables.project_id=#{@selectedproject} and data_set_variables.data_set_id is null ").order("data_set_variables.name").all
    end
    if @envone != nil and @envtwo == nil
      if data_set_variable == nil
        @data_set_variable = nil
      else
        @data_set_variable = DataSetVariable.select("data_set_variables.*, envone.value as valueone, envone.id as idvarone").joins("INNER JOIN data_set_variables as envone on envone.domaine_id = data_set_variables.domaine_id and envone.data_set_id = #{envone} and envone.init_variable_id = data_set_variables.id ").where("data_set_variables.id = #{data_set_variable.id}").first
      end
      @data_set_variables = DataSetVariable.select("data_set_variables.*, envone.value as valueone, envone.id as idvarone").joins("INNER JOIN data_set_variables as envone on envone.domaine_id = data_set_variables.domaine_id and envone.data_set_id = #{envone} and envone.init_variable_id = data_set_variables.id ").where("data_set_variables.domaine_id = #{@domaine} and data_set_variables.project_id=#{@selectedproject} and data_set_variables.data_set_id is null ").order("data_set_variables.name").all
    end	
    if @envone != nil and @envtwo != nil
      if data_set_variable == nil
        @data_set_variable = nil
      else
        @data_set_variable = DataSetVariable.select("data_set_variables.*, envone.value as valueone, envone.id as idvarone, envtwo.value as valuetwo, envtwo.id as idvartwo").joins("INNER JOIN data_set_variables as envone on envone.domaine_id = data_set_variables.domaine_id and envone.data_set_id = #{envone} and envone.init_variable_id = data_set_variables.id INNER JOIN data_set_variables as envtwo on envtwo.domaine_id = data_set_variables.domaine_id and envtwo.data_set_id = #{envtwo} and envtwo.init_variable_id = data_set_variables.id ").where("data_set_variables.id = #{data_set_variable.id}").first
      end
      @data_set_variables = DataSetVariable.select("data_set_variables.*, envone.value as valueone, envone.id as idvarone, envtwo.value as valuetwo, envtwo.id as idvartwo").joins("INNER JOIN data_set_variables as envone on envone.domaine_id = data_set_variables.domaine_id and envone.data_set_id = #{envone} and envone.init_variable_id = data_set_variables.id INNER JOIN data_set_variables as envtwo on envtwo.domaine_id = data_set_variables.domaine_id and envtwo.data_set_id = #{envtwo} and envtwo.init_variable_id = data_set_variables.id ").where("data_set_variables.domaine_id = #{@domaine} and data_set_variables.project_id=#{@selectedproject} and data_set_variables.data_set_id is null ").order("data_set_variables.name").all
    end	
  
    respond_to do |format|
      if @data_set_variable !=nil 
        format.html { redirect_to @data_set_variable, notice: 'DOMelement was successfully created.' }
        format.js   {}
        format.json { render json: @data_set_variable, status: :created, location: @data_set_variable }
      else
        format.html { redirect_to  controller: 'data_set_variables', action: 'index'  , message: @message, ok: 'ko' }

app/views/data_set_variables/_data_set_variable.html.erb
<% if @message != nil and data_set_variable.id.to_s == @majid.to_s %>
   <span id='idspanmessage' class='<% if @OK %>succesMessage<% else %>errorMessage<% end %>' onclick='this.parentNode.removeChild(this)' style='vertical-align: top;'><%= @message %>&nbsp;<b>x</b></span>
  <% end %> 

<div class="ligthline">
<div class="inline">

<form style="display:inline" onsubmit="startloader();" action="/data_set_variables/update" data-remote="true" rel="nofollow" data-method="put" id="formupdt<%= data_set_variable.id %>">
    <input type="hidden" name="filtername" value="<%= @name %>"/>
    <input type="hidden" name="filterdesc" value="<%= @description %>"/>
    <input type="hidden" name="idelement" value="<%= data_set_variable.id %>"/>
	<% if @envone != nil %>
		<input type="hidden" name="envone" value="<%= @envone.id %>"/>
	<% end %>
	<% if @envtwo != nil %>
		<input type="hidden" name="envtwo" value="<%= @envtwo.id %>"/>
	<% end %>

	
	
	<input <% if @can_manage_jdd == 0 %>disabled<% end %> pattern="\$[A-Za-z0-9_]{2,50}" maxlength='50' onKeyUp="formatasvariable(this)"  required <% if @envtwo != nil %>size='20'<% else %>size='25'<% end %>  class='inputboxlist' type="text" spellcheck='false' name="name" id="iname<%= data_set_variable.id %>" value="<%= data_set_variable.name %>" title="<%= data_set_variable.name %>" onKeyDown='showvalidbtnid("<%= data_set_variable.id %>");' onchange='checknamevalidity("<%= data_set_variable.id %>", "<%= data_set_variable.name %>");'  />

			
  <% if @envone != nil %>
	<input <% if @can_manage_jdd == 0 %>disabled<% end %> type="text" spellcheck='false' onKeyUp="formatslash(this);" class='inputboxlist' placeholder="<%= t('valeur_pour') %> <%= @envone.name %>" name="valueone" id="idvalueone<%= data_set_variable.id %>" <% if @envtwo != nil %>size='50'<% else %>size='70'<% end %> maxlength='255' value="<%= data_set_variable.valueone.to_s %>" title="<%= data_set_variable.valueone.to_s %>" onKeyDown='showvalidbtnid("<%= data_set_variable.id %>");'/>
  <% end %>

  <% if @envtwo != nil and @envone != nil  %><% if @can_manage_jdd == 1 %>
        <button class="btndroite" onclick="document.getElementById('idvaluetwo<%= data_set_variable.id %>').value=document.getElementById('idvalueone<%= data_set_variable.id %>').value;" title="<%= t('ecr_variable_env.copier_la_valeur_vers') %>"></button>
       <% end %> <input <% if @can_manage_jdd == 0 %>disabled<% end %> type="text" spellcheck='false' onKeyUp="formatslash(this);"  class='inputboxlist' placeholder="<%= t('valeur_pour') %> <%= @envtwo.name %>" name="valuetwo" id="idvaluetwo<%= data_set_variable.id %>" size='50' maxlength='255' value="<%= data_set_variable.valuetwo.to_s %>" title="<%= data_set_variable.valuetwo.to_s %>" onKeyDown='showvalidbtnid("<%= data_set_variable.id %>");'/>
  <% end %>

 	<input <% if @can_manage_jdd == 0 %>disabled<%end%> type='checkbox' name='isn' id='isn<%= data_set_variable.id %>' <%if data_set_variable.is_numeric.to_s == "1"%>checked<%end%> onclick="showvalidbtnid(<%= data_set_variable.id %>);if (this.checked==true) {document.getElementById('isb<%= data_set_variable.id %>').checked=false;}"></input><span class="textStyle"><%= t('numeric')%></span>
	<input <% if @can_manage_jdd == 0 %>disabled<%end%> type='checkbox' name='isb' id='isb<%= data_set_variable.id %>' <%if data_set_variable.is_boolean.to_s == "1"%>checked<%end%> onclick="showvalidbtnid(<%= data_set_variable.id %>);if (this.checked==true) {document.getElementById('isn<%= data_set_variable.id %>').checked=false;}"><span class="textStyle"><%= t('boolean')%></span></input>
	<input <% if @can_manage_jdd == 0 %>disabled<% end %> type="text" spellcheck='false' class='inputboxlist' placeholder="<%= t('description') %>" name="description" id="idescription<%= data_set_variable.id %>" <% if @envtwo != nil %>size='10'<% else %>size='50'<% end %> value="<%= data_set_variable.description %>" title="<%= data_set_variable.description %>"  onKeyDown='showvalidbtnid("<%= data_set_variable.id %>");'/>
 
  
    <input style="display:none" class="btnvalid" title="<%= t('valider') %>" id="btnval<%= data_set_variable.id %>" type="submit" value="" onmouseover='checknamevalidity("<%= data_set_variable.id %>", "<%= data_set_variable.name %>");' style='vertical-align: top;'/>
</form>  
        
<% if @can_manage_jdd == 1 and (data_set_variable.is_used == nil or data_set_variable.is_used == 0) %>
    <%= button_to "", data_set_variable_path(data_set_variable), params: {filtername: @name, filterdesc: @description, envone: @envone, envtwo: @envtwo}, remote: true, method: :delete, form: {onsubmit: "startloader();"}, data: { confirm: "#{t('ecr_variable_env.confirme_supp')} #{data_set_variable.name}?" }, class: "btndel", title: t('supprimer') %>
<% end %>




</div>
</div>
<script>
          setTimeout(function () {
            elem = document.getElementById('idspanmessage');
            if (elem!=null) {
              elem.parentNode.removeChild(elem);
            }
        }, 2000);
</script>  

app/views/data_set_variables/_head.html.erb
<span class="titleStyle" style="color:#161616"><b>&nbsp;&nbsp;<%= t('ecr_variable_env.nouvelle_variable') %>&nbsp;&nbsp;</b></span> 
<br>
<div style="display: inline-block">
	<div style="display: inline">
		<form onsubmit="startloader();" class="new_data_set_variable" id="new_data_set_variable" action="/data_set_variables" accept-charset="UTF-8" data-remote="true" method="post" style="display: inline;margin-left: 7px;">
			 <input  pattern="\$[A-Za-z0-9_]{2,50}" maxlength='50' onKeyUp="formatasvariable(this)" required size=30 class='inputboxlist' type="text" spellcheck='false' name="name" id="data_set_variable_data_set_variable_name" placeholder="<%= t('nom') %>" title="<%= t('ecr_variable_env.format_titre') %>"/>
			 <textarea spellcheck='false' class='inputboxlist' name="description" id="data_set_variable_data_set_variable_description" rows='1' cols='50' placeholder="<%= t('description') %>"></textarea>
			<% if @can_manage_jdd == 1 and @envone != nil %>
			  <input type="submit" class="btnadd" title="<%= t('ajouter') %>" value="" ></input>
			<% end %>
			<input type="hidden" name="envone" value="<% if @envone != nil %><%= @envone.id %><% end %>"/>
			<input type="hidden" name="envtwo" value="<% if @envtwo != nil %><%= @envtwo.id %><% end %>"/>  
		</form>  
		<button class="btnsearch" onclick="document.getElementById('data_set_variable_data_set_variable_name').value=document.getElementById('data_set_variable_data_set_variable_name').value.replace('$','');startloader();searchvar();" title="<%= t('chercher') %>"></button>
	  
		<div style="float: right;display: inline;">
			<span style="textStyle">Voir &nbsp;</span>
			<select id="envone" class="lookupbox" >
				<option <%  if @envone == nil %>selected<% end %>  value="">-</option>
				<% if @data_sets != nil  
				@data_sets.each do |env| %>
				<option <%  if @envone != nil  and @envone.id == env.id %>selected<% end %> value="<%= env.id %>"><%= env.name  %></option>
			  <% end 
			end %>
			</select>
			<% if @can_manage_jdd == 1 %>
			<button class="btndroite" onclick="document.getElementById('pasteidenvone').value=document.getElementById('envone').value;document.getElementById('pasteidenvtwo').value=document.getElementById('envtwo').value;startloader();document.getElementById('formpasteall').submit();" title="<%= t('ecr_variable_env.copier_les_valeurs_vers') %>"></button>
			<% end %>
			<select id="envtwo" class="lookupbox" >
				<option <%  if @envtwo == nil %>selected<% end %>  value="">-</option>
				<% if @data_sets != nil  
				@data_sets.each do |env| %>
				<option <%  if @envtwo !=nil and @envtwo.id == env.id %>selected<% end %> value="<%= env.id %>"><%= env.name  %></option>
			  <% end 
			end %>
			</select>  
			<button class="btnrefresh" title="<%=  t('recharger') %>" onclick="document.getElementById('searchidenvone').value=document.getElementById('envone').value;document.getElementById('searchidenvtwo').value=document.getElementById('envtwo').value;startloader();document.getElementById('formsearch').submit();"></button>
		</div>  
	</div>
</div>	  
    
<form onsubmit="startloader();" id="formsearch" action="../data_set_variables/index" method="post">
	<input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token"/>
    <input type="hidden" name="description" id="searchdesc" value=""/>
    <input type="hidden" name="name" id="searchname" value=""/>   
    <input type="hidden" name="envone" id="searchidenvone" value="<% if @envone != nil %><%= @envone.id %><% end %>"/>
    <input type="hidden" name="envtwo" id="searchidenvtwo" value="<% if @envtwo != nil %><%= @envtwo.id %><% end %>"/>
    <input type="hidden" name="do" value="search"/>
</form>            

<form onsubmit="startloader();" id="formpasteall" action="../data_set_variables/index" method="post">
<input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token"/>
    <input type="hidden" name="description" id="pastedesc" value=""/>
    <input type="hidden" name="name" id="pastename" value=""/>   
    <input type="hidden" name="envone" id="pasteidenvone" value="<% if @envone != nil %><%= @envone.id %><% end %>"/>
    <input type="hidden" name="envtwo" id="pasteidenvtwo" value="<% if @envtwo != nil %><%= @envtwo.id %><% end %>"/>
    <input type="hidden" name="do" value="paste"/>
</form>   

app/views/data_set_variables/create.js.erb
$("<%= escape_javascript(render @data_set_variable) %>").appendTo("#data_set_variables");
$('#data_set_variable_data_set_variable_name').val('');
$('#data_set_variable_data_set_variable_description').val('');
stoploader();

app/views/data_set_variables/destroy.js.erb
$('#data_set_variables').html('<%= j(render @data_set_variables, locals: {data_set_variable: @data_set_variable} )%>');
stoploader();

app/views/data_set_variables/index.html.erb
<script type="application/javascript"> 
function searchvar() {
    document.getElementById('data_set_variable_data_set_variable_name').required=false;
    document.getElementById('searchname').value=document.getElementById('data_set_variable_data_set_variable_name').value;
    document.getElementById('searchdesc').value=document.getElementById('data_set_variable_data_set_variable_description').value;
    document.getElementById('formsearch').submit();
}


</script>

<div id="scrollablecontent">
	<div >
		<div class="popupadd">
			<%= render :partial => 'data_set_variables/head' %>             
		</div> 

		<% if @message != nil  %>
			<span id='idspanmessage' class='<% if @OK %>succesMessage<% else %>errorMessage<% end %>' onclick='this.parentNode.removeChild(this)' style='vertical-align: top;'><%= @message %>&nbsp;<b>x</b></span>
		<% end %>
		
		<div id="data_set_variables">	
			<% if @data_set_variables != nil %>    
				<%= render  @data_set_variables %>
			<% end %>
		</div>
	</div>
</div>

app/views/data_set_variables/update.js.erb
$('#data_set_variables').html('<%= j(render @data_set_variables, locals: {data_set_variable: @data_set_variable} )%>');
stoploader();